src/common/components/modal/index.styles.ts, src/common/components/searchInput/index.tsx, src/common/components/tabBar/index.styles.ts, src/pages/main/components/categoryBar/index.tsx, src/pages/main/styles/BottomSheet.style.ts, src/pages/main/styles/CategoryBar.style.ts, src/pages/main/styles/index.style.ts
- https://ureca7.atlassian.net/browse/SV-135
- 메인페이지 z-index를 전반적으로 수정하였습니다.
- 메인페이지에서 검색 바 클릭시 검색 페이지로 라우팅 되도록 구현하였습니다.
- 
<br><br>
=> fix/SV-135: 모달, 탭바, 카테고리바, 바텀시트  z-index 조절

src/service/apis/index.ts
- https://ureca7.atlassian.net/browse/SV-231
- 인스턴스 생성했습니다. 이제 여기서 갖다 써주세요 ~
- 
<br><br>
=> feat/SV-231: axios 인스턴스 생성 및 인터셉터 추가

src/pages/todaymungWrite/queries/index.ts
- https://ureca7.atlassian.net/browse/SV-256
- 
- 
<br><br>
=> hotfix/SV-256: 리뷰등록, 오늘멍 등록 실패시에도 리뷰, 오늘멍 기록 전체 삭제

src/pages/main/index.tsx
- https://ureca7.atlassian.net/browse/SV-249
- 
- 
<br><br>
=> fix/SV-249: 마커 수가 여러개인 경우 마커에 찍히지 않는 문제 수정

src/pages/todaymung/index.tsx, src/pages/todaymungDetail/index.tsx, src/pages/todaymungPlaceRegist/index.tsx
- https://ureca7.atlassian.net/browse/SV-215
- 모두 로딩중 로티로 적용하였습니다
- 
<br><br>
=> feat/SV-215: 로딩중 적용 안된 페이지 로딩 컴포넌트로 수정

src/pages/signUp/components/DatePicker.tsx, src/pages/signUp/components/DaumPost.tsx, src/pages/signUp/index.tsx, src/pages/userEdit/index.tsx
- 유저 도로명 주소 등록 DaumPost(위도,경도 적용) 구현
- 생년월일 DatePicker 스타일 커스텀
- 마이페이지 스타일 상세 수정 추가
>
- 
<br><br>
=> feat/SV-18: 유저 도로명 주소 등록 DaumPost(위도,경도 적용) 구현, 생년월일 DatePicker 스타일 커스텀, 마이페이지 스타일 상세 수정 추가

src/common/components/layout/index.tsx, src/pages/main/components/bottomSheet/index.tsx, src/pages/main/index.tsx, src/pages/recommend/components/IndexGuest.tsx, src/pages/recommend/components/RecommendCard.tsx, src/pages/todaymungPlaceRegist/queries/index.ts
- https://ureca7.atlassian.net/browse/SV-215
- 추천페이지에서 blur을 클릭해도 이벤트 캡쳐링으로 인해 라우팅 되는 것을 방지하였습니다.
- 
<br><br>
=> fix/SV-215: 추천페이지 이벤트 캡쳐링 방지

src/pages/main/styles/CategoryBar.style.ts, src/pages/recommend/components/IndexGuest.tsx, src/pages/recommend/components/RecommendCard.tsx, src/pages/todaymungPlaceRegist/styles/index.style.ts, src/service/apis/index.ts
- https://ureca7.atlassian.net/browse/SV-215
- axios request intercepto를 적용하였습니다.
- 
<br><br>
=> feat/SV-215: axios request interceptor 적용

src/pages/login/index.tsx, src/pages/login/styles/login.styles.ts
=> fix/SV-215: 로그인 화면 스크롤 가능하도록 수정

src/common/components/layout/index.tsx, src/common/constants/route.ts, src/pages/dogEdit/index.tsx, src/pages/dogEdit/styles/dogsEdit.styles.ts, src/pages/dogs/index.tsx, src/pages/dogs/styles/dogs.styles.ts, src/pages/main/styles/CategoryBar.style.ts, src/pages/my/components/myDogs/index.tsx, src/pages/my/components/profile/index.tsx, src/pages/my/index.styles.ts, src/pages/my/index.tsx, src/route/Router.tsx, src/styles/GlobalStyles.ts
- https://ureca7.atlassian.net/browse/SV-293
- https://ureca7.atlassian.net/browse/SV-300
- https://ureca7.atlassian.net/browse/SV-302
- https://ureca7.atlassian.net/browse/SV-307
- https://ureca7.atlassian.net/browse/SV-308
- https://ureca7.atlassian.net/browse/SV-310
- https://ureca7.atlassian.net/browse/SV-301
- 반려견 등록 페이지 url을 /my/dogs/add로 설정하고, 관련 사항들을 모두 수정하였습니다.
- 반려견 수정 페이지로 navigate 시 userNickname과 dogData를 넘겨주도록 수정하였습니다.
- globalStyle에서 기본 폰트 색을 검정색으로 설정했습니다.
- 로그아웃 버튼과 바텀 바 간격이 좁은 문제를 해결했습니다.
- 
<br><br>
=> fix/SV-293: 반려견 등록 페이지 및 수정 페이지 수정

src/pages/todaymungDetail/queries/index.ts, src/pages/todaymungPlaceRegist/index.tsx, src/pages/todaymungPlaceRegist/styles/index.style.ts, src/pages/todaymungWrite/index.tsx, src/pages/todaymungWrite/queries/index.ts
- https://ureca7.atlassian.net/browse/SV-290
- 오늘멍 리뷰 등록과 오늘멍 등록을 동시에 처리할 경우 데드락 문제가 발생하 프론트에서 등록 페이지를 나누어 처리하였습니다.
- 
<br><br>
=> feat/SV-290: 오늘멍 리뷰 등록 및 오늘멍 등록 로직 분리

src/pages/signUp/components/DaumPost.tsx, src/pages/signUp/styles/signUp.styles.ts
=> feat/SV-18: 회원가입 GenderSelect 버튼 크기 input 크기 조절

src/pages/my/styles/profile.styles.ts
=> fix/SV-293: 강아지 카드 컴포넌트 스타일 수정 (flex:1 제거)

src/pages/signUp/styles/signUp.styles.ts, src/pages/userEdit/index.tsx
=> fix/SV-293: 유저 정보 페이지 관련 스타일 수정

src/pages/main/components/bottomSheet/Content.tsx
- https://ureca7.atlassian.net/browse/SV-293
- content 컴포넌트에서 category가 잘못 나오는 문제를 해결했습니다.
- 
<br><br>
=> fix/SV-293: content 컴포넌트에서 category가 잘못 나오는 문제 해결

src/pages/recommend/components/IndexGuest.tsx
=> chore/SV-328: 임시 로컬스토리지 초기화 버튼 구현

src/pages/my/index.tsx
- https://ureca7.atlassian.net/browse/SV-214
- 
- 
<br><br>
=> fix/SV-214: 마이페이지 로딩 스피너 로티 부착

src/main.tsx
=> fix/SV-214: 배포용 url 센트리에 추가

index.html, src/main.tsx
- https://ureca7.atlassian.net/browse/SV-214
- 오픈 그래프 메타태그를 설정하였습니다
- 
<br><br>
=> feat/SV-214: OpenGraph 메타 태그 설정 

src/pages/todaymungWrite/components/MediaGroup.tsx
- https://ureca7.atlassian.net/browse/SV-331
-  오늘 멍 작성 시 동영상을 올릴 경우 preview에서 엑박으로 보이던 것 수정하였습니다. (+ mediaUrl이 올바르지 않을 때 예외처리 하였습니다)
- 
<br><br>
=> feat/SV-331: 오늘멍 작성 시 동영상 preview 보이게 끔 수정

src/pages/detail/index.tsx
- 시설 상세 페이지 undefined 관련 버그 수정
- 
<br><br>
=> hotfix/SV-368: 시설 상세 페이지 undefined 관련 버그 수정

src/pages/detail/index.tsx, src/pages/todaymung/components/noDiaryList/index.tsx, src/pages/todaymung/components/registButton/index.tsx
- https://ureca7.atlassian.net/browse/SV-331
- 버튼 삼항연산자 반대로 수정하고 리스트뷰 기본 default active값 수정
- 
<br><br>
=> release 1.0.4 : 오늘멍 기존에 작성되어있다고 나오는 버그 수정

src/pages/detail/index.tsx
- 시설 상세 페이지 렌더링 버그 수정
- 
<br><br>
=> hotfix/SV-368: 시설 상세 페이지 렌더링 버그 수정

src/pages/detail/index.tsx, src/pages/main/components/bottomSheet/Content.tsx, src/pages/todaymungDetail/index.tsx, src/pages/todaymungEdit/queries/index.ts, src/pages/todaymungPlaceRegist/index.tsx, src/pages/todaymungPlaceRegist/queries/index.ts, src/pages/todaymungWrite/index.tsx, src/pages/todaymungWrite/queries/index.ts
=> hotfix/SV-368: 훅 렌더링 버그 수정

src/pages/login/components/KakaoCallbackHandler.tsx
- https://ureca7.atlassian.net/browse/SV-364
- 사용자가 로그인에 성공하면 2.5초간 놀멍 로티가 보여지고, 이후 메인 페이지로 이동하는 기능을 추가했습니다.
- 
<br><br>
=> feat/SV-364: 로그인 후 2.5초간 놀멍 로티 적용

src/common/components/layout/index.tsx, src/common/components/loginPromptModal/index.style.ts, src/main.tsx, src/pages/main/queries/index.ts, src/pages/signUp/components/DaumPost.tsx, src/pages/signUp/index.tsx, src/pages/userEdit/index.tsx
- 뒤로가기 버그 수정 및 sentry url 재설정
- 
<br><br>
=> hotfix/SV-368: 뒤로가기 버그 수정 및 sentry url 재설정

src/common/components/header/index.styles.ts, src/common/components/layout/index.tsx, src/common/components/lottie/index.style.ts, src/common/components/tabBar/index.styles.ts, src/common/constants/ui.ts, src/pages/recommend/components/RecommendCard.tsx, src/pages/recommend/styles/RecommendCard.style.ts, src/pages/todaymungWrite/components/VisitedPlaceCard.tsx, src/pages/todaymungWrite/styles/VisitedPlaceCard.style.ts
- https://ureca7.atlassian.net/browse/SV-364
- 카카오 리다이랙트 페이지에서 상단바 및 하단바 나오는 문제 수정
- 상단바 및 하단바 높이 수정
- 상단바 및 하단바 높이 값 상수로 변경
- 오늘멍 작성하기에서 장소 카드 css 수정
- 
<br><br>
=> feat/SV-364: 놀멍 로티 수정, header 및 bottom bar 수정

src/pages/main/components/bottomSheet/index.tsx
- 바텀시트 필터에 GA 이벤트 부착
- 
<br><br>
=> feat/SV-368: 바텀시트 필터에 GA 이벤트 부착
